# Generated by Django 5.2.7 on 2026-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('plato_fuerte', 'Plato Fuerte'), ('bebida', 'Bebida'), ('postre', 'Postre'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
    ]
