# Generated by Django 5.2.7 on 2025-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte'), ('consumidor_final', 'Consumidor Final')], default='cedula', max_length=20)),
                ('numero_documento', models.CharField(max_length=13, unique=True, verbose_name='Número de Identificación')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
