# Generated by Django 5.2.7 on 2025-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula_o_ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RUC/CI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo/Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
