# Generated by Django 5.2.7 on 2025-12-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula_o_ruc',
            field=models.CharField(default='0000000000', max_length=13, unique=True, verbose_name='RUC/CI'),
            preserve_default=False,
        ),
    ]
