"""
Django settings for restaurante project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

import re
from django.core.exceptions import ValidationError

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import sys
sys.path.append(os.path.join(BASE_DIR, 'app'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'core',
    'usuarios',
    'pedidos',
    'inventario',
    'clientes',
    'caja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- Para servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.UpdateLastActivityMiddleware', # Middleware propio
]

ROOT_URLCONF = 'restaurante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurante.wsgi.application'

# Axes para restrer y blockear el acceso
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    # El backend por defecto de Django
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'restaurante_db',
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),  
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


class SpecialCharacterValidator:
    def validate(self, password, user=None):
        if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
            raise ValidationError(
                "La contraseña debe contener al menos un carácter especial.",
                code='password_no_special_char',
            )

    def get_help_text(self):
        return "Tu contraseña debe contener al menos un carácter especial."

AUTH_PASSWORD_VALIDATORS = [

  {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'usuarios.validators.CustomPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True

# --- CONFIGURACIÓN DE SEGURIDAD DE SESIONES ---
# Cierra la sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Tiempo de inactividad: 15 minutos (900 segundos)
SESSION_COOKIE_AGE = 900 
# Actualizar el tiempo de expiración en cada petición (para que sean 15 min de INACTIVIDAD, no absolutos)
SESSION_SAVE_EVERY_REQUEST = True
# Asegura que la cookie no se pueda acceder por JS
SESSION_COOKIE_HTTPONLY = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Compresión y caché para estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = '/usuarios/login/'
LOGOUT_REDIRECT_URL = '/usuarios/login/' # Con esto redirije a mi pagina de login 
LOGIN_REDIRECT_URL = '/'

# Configuracion de Jazzmin

JAZZMIN_SETTINGS = {
    # Títulos y Logos
    "site_title": "Restaurante Admin",
    "site_header": "Restaurante App",
    "site_brand": "Restaurante App",
    "welcome_sign": "Bienvenido al Panel de Control",
    "copyright": "El Rincón que No Conoces",
    
    # Menú lateral
    "search_model": ["usuarios.Usuario", "pedidos.Pedido"],

    # Iconos (Puedes añadir más aquí)
    "icons": {
        "auth": "fas fa-users-cog",
        "usuarios.Usuario": "fas fa-user",
        "usuarios.AuditLog": "fas fa-clipboard-list", # Icono de auditoría
        "pedidos.Mesa": "fas fa-chair",
        "pedidos.Producto": "fas fa-utensils",
        "pedidos.Pedido": "fas fa-receipt",
    },
    
    # Orden del menú lateral
    "order_with_respect_to": ["pedidos", "usuarios", "auth"],

    # Opciones de interfaz
    "show_ui_builder": True, # <-- ¡Esto te dejará probar colores en vivo!
}

JAZZMIN_UI_TWEAKS = {
    # --- ESTILO GENERAL (Blanco y Limpio como en la foto) ---
    "theme": "litera", # Un tema con fuentes limpias y fondo blanco
    # "theme": "flatly", # Otra opción buena si 'litera' no te convence
    
    # --- BARRA SUPERIOR (Blanca limpia) ---
    "navbar": "navbar-white navbar-light",
    
    # --- BARRA LATERAL (Blanca con acentos naranjas) ---
    "sidebar": "sidebar-light-warning", 
    # Nota: 'warning' es el código de color para el Naranja en estos temas.
    
    # --- COLORES DE ACENTO (Botones y selectores naranjas) ---
    "accent": "accent-warning",
    "brand_colour": "navbar-warning",
    
    # --- DETALLES ---
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-warning", # Botones principales naranjas
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Configuración de AXES
AXES_FAILURE_LIMIT = 5  # Bloqueo después de 5 intentos
AXES_COOLOFF_TIME = 0.10 # Bloqueo por 15 minutos (0.25 horas)
AXES_LOCKOUT_TEMPLATE = 'usuarios/lockout.html' # Plantilla a mostrar
AXES_RESET_ON_SUCCESS = True # Resetea los intentos fallidos si el login es exitoso
# Blockear el acceso por el nombre y no por la ip 
AXES_LOCKOUT_PARAMETERS = ["username"]
AXES_LOCKOUT_TEMPLATE = 'usuarios/lockout.html'
AXES_RESET_ON_SUCCESS = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# =============================
# Configuración de correo real (Gmail SMTP)
# =============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Tu correo Gmail y contraseña de aplicación
# Tu correo Gmail y contraseña de aplicación
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Dirección de envío por defecto
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Cierra la sesión si el navegador se cierra
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Tiempo de vida de la cookie (en segundos). 900 seg = 15 minutos.
SESSION_COOKIE_AGE = 900

# Para que el contador se reinicie cada vez que el usuario hace clic en algo
SESSION_SAVE_EVERY_REQUEST = True