# Generated by Django 5.2.7 on 2026-01-17 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial en Caja')),
                ('monto_final_sistema', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Ventas (Sistema)')),
                ('monto_final_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero en Mano')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='¿Caja Abierta?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
