# Generated by Django 5.2.7 on 2025-11-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cocina', 'Cocinero'), ('gerente', 'Gerente')], default='mesero', max_length=10),
        ),
    ]
