# Generated by Django 5.2.7 on 2026-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
